### ISSUE TITLE
Continued Pre-training or Pretrained from Scratch?

### ISSUE THREAD

**Issue by aflah02** [huggingface/olm-training#5]
Hi!
Thanks for the great work on creating these models. I have some questions regarding the training of these models. Firstly, do these models build on top of the public roberta checkpoints? or do they pre-train right from scratch? From what I could gather, it's the latter but would like to be sure about the same. Secondly, I have a question regarding this text present on the HF page for the model - 

 "The model and tokenizer were trained with this [December 2022 cleaned Common Crawl dataset](https://huggingface.co/datasets/olm/olm-CC-MAIN-2022-49-sampling-ratio-olm-0.15114822547) plus this [December 2022 cleaned Wikipedia dataset (https://huggingface.co/datasets/olm/olm-wikipedia-20221220).
The tokenized version of these concatenated datasets is [here](https://huggingface.co/datasets/olm/olm-december-2022-tokenized-512).
The datasets were created with this [repo](https://github.com/huggingface/olm-datasets)."

Does this uptodate common crawl also have all of the old data which was used for the original RoBERTa? Can I find any analysis on how much data overlaps between the two?

**Comment by aflah02** [comment]
Also can you share some citation info? How should I cite your work?

**Comment by aflah02** [comment]
@TristanThrush @Muhtasham Can you please respond to these queries?

**Comment by Muhtasham** [comment]
Hi @aflah02,

Sorry for late reply, the models are trained from scratch. 

Regarding analysis on how much data overlaps between the original dataset and the you may have to do it manually, 

Afaik RoBERTa model was pretrained on the reunion of five datasets:

[BookCorpus](https://yknzhu.wixsite.com/mbweb), a dataset consisting of 11,038 unpublished books;
[English Wikipedia](https://en.wikipedia.org/wiki/English_Wikipedia) (excluding lists, tables and headers) ;
[CC-News](https://commoncrawl.org/2016/10/news-dataset-available/), a dataset containing 63 millions English news articles crawled between September 2016 and February 2019.
[OpenWebText](https://github.com/jcpeterson/openwebtext), an opensource recreation of the WebText dataset used to train GPT-2,
[Stories](https://arxiv.org/abs/1806.02847) a dataset containing a subset of CommonCrawl data filtered to match the story-like style of Winograd schemas.

And at least the Wikipedia part should overlap. 

Just FYI: @TristanThrush is no longer maintaining this repo, due to start of his PhD

**Comment by aflah02** [comment]
Thanks @Muhtasham 
Can you also provide instructions on how to cite your work? Any bibtex entry etc.?

**Comment by Muhtasham** [comment]
Sorry for previous answer, I think [this](https://github.com/huggingface/olm-datasets#analyzing-the-corpora) may benefit you

> Can you also provide instructions on how to cite your work? Any bibtex entry etc.?

You can just cite the repo 😀 

```
@software{olm,
  author= {Thrush, Tristan and
Ngo, Helen and, 
Bekman, Stas and,
Oblokulov, Muhtasham},
  title = {Online Language Modelling Training Pipeline},
  howpublished = {\url{https://github.com/huggingface/olm-training}},
  year = 2022,
  month = December
}
```

**Comment by aflah02** [comment]
Thankss a lot for all the help!! and also really thankful for this cool work!
